# Generated by Django 3.2.9 on 2021-11-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sondageapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='body',
            new_name='choice',
        ),
    ]
