# Generated by Django 3.2.9 on 2021-11-11 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sondageapp', '0002_rename_body_response_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='inquiry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sondageapp.inquiry'),
        ),
    ]
