# Generated by Django 3.2.9 on 2021-11-12 00:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sondageapp', '0003_alter_question_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='date_created',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
