# Generated by Django 3.2.9 on 2021-11-15 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondageapp', '0005_auto_20211112_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='other',
            field=models.CharField(default='none', max_length=250),
        ),
    ]
