# Generated by Django 3.2.9 on 2021-11-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sondageapp', '0007_response_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='type',
            field=models.IntegerField(choices=[(1, 'Choix'), (2, 'Autre')], default=1),
        ),
    ]
